
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'kpi_data_project'
version: '1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'kpi_data_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  kpi_data_project:
    staging:
      +materialized: view
    mart:
      core:
        +materialized: table
      dim_cmi:
        +materialized: table
      dim_finance:
        +materialized: table
      dim_mars:
        +materialized: table
      dim_media:
        +materialized: table
      dim_ppd:
        +materialized: table
      dim_refProduct:
        +materialized: table
      dim_sales:
        +materialized: table
      dim_social_influencer:
        +materialized: table
